version: '3.8'

services:
  ha-history-mcp:
    # Use published image by default (comment out 'image' and uncomment 'build' for local development)
    image: ghcr.io/jtenniswood/ha-history-mcp:latest
    
    # Uncomment the lines below for local development
    # build: .
    
    container_name: ha-history-mcp-server
    restart: unless-stopped
    
    environment:
      # Home Assistant Configuration
      - HA_URL=${HA_URL}
      - HA_TOKEN=${HA_TOKEN}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30}
      
      # Python Configuration  
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Optional: Mount logs directory
    # volumes:
    #   - ./logs:/app/logs

  # Development service (for local development with auto-rebuild)
  ha-history-mcp-dev:
    build: .
    container_name: ha-history-mcp-dev
    restart: "no"  # Don't auto-restart in development
    profiles:
      - dev
    
    environment:
      - HA_URL=${HA_URL}
      - HA_TOKEN=${HA_TOKEN}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - LOG_LEVEL=DEBUG  # More verbose logging for development
    
    # Mount source code for development
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    
    security_opt:
      - no-new-privileges:true